### ISSUE TITLE
Tree is showing a trunk of unuseful folders

### ISSUE THREAD

**Issue by wamasimba** [angular-architects/detective#25]
# Issue

I tend to use detective in repos that have also API, backend and BFF implementations. That means that our front-end code resides in a deeper folder, e.g. my entry point is at `/App/FrontEnd/src/main.ts`; this means no relevant analyzable code is outside the folder `/App/FrontEnd/src`; I would like to see the tree pruned with these unuseful folders.

I came up with the idea to change the last few lines of `inferFolders()` to:
```ts
  let converted = toFolder(root);
  while (converted.folders.length === 1 && converted.folders[0].folders.length === 1) converted = converted.folders[0];
  return converted.folders;
```

This seems to work for me, but I realize this will also prune folders that do contain interesting stuff; looking  for a better idea.

**Comment by manfredsteyer** [comment]
Hi,

Thanks for pointing this out. Yes, this is something we should look into. 

I'm thinking about adding a context menu to each tree entry. It could contain an option "focus". If an item has the focus, it becomes the root node of the shown tree. We could also store this setting in the detective.conf.json. And we need a reset button somewhere.

What do you think about this idea?

Best,
Manfred

**Comment by wamasimba** [comment]
I see what you mean, so I implemented it, see https://github.com/angular-architects/detective/pull/30
