### ISSUE TITLE
offer to add linter 

### ISSUE THREAD

**Issue by evoytenkoapps** [angular-architects/detective#29]
# Issue

is it possible to add a linter analogue?
for example, I create a rule that for component x there should not be more than 20 imports
or for this module the ratio of imports to its usage should be 20%
And if the rules are violated, then the job crashes in ci?

**Comment by manfredsteyer** [comment]
Hi,

this is currently out of scope for our plans. We really want to focus on forensic analysis. For the mentioned use case, I would go with an existing linting rule.
